import { Project } from './types';

export const mockProjects: Project[] = [
  {
    id: 'usc-isi-1',
    title: 'USC ISI Autonomous Science Agents',
    description: 'AI copilots that orchestrate complex experimental workflows for national labs',
    longDescription:
      'USC Information Sciences Institute is building autonomous science agents that help research teams plan, simulate, and validate high-stakes experiments. The system blends task-decomposed large language models with verified control policies so labs can safely accelerate materials discovery, chip design, and biosafety research. Initial deployments focus on integrating with Department of Energy user facilities and publishing a reproducibility benchmark so other labs can audit agent decisions.',
    category: 'AI Safety & Alignment',
    imageUrl:
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1600&q=80',
    videoUrl: 'https://www.youtube.com/embed/6jdaj0yOHGs',
    fundingGoal: 900000,
    currentFunding: 485000,
    stakedAmount: 430000,
    backers: 1612,
    daysLeft: 34,
    creator: '0xF8bAbC0f3E84a8f1d5A6E6A4c6d2F5b4E6aaB3c2',
    createdAt: new Date('2024-02-10'),
    matchingPool: 150000,
    quadraticScore: 9.4,
    acceptedTokens: ['USDC', 'DAI', 'NOVA'],
    researchArea: 'Autonomous Systems',
    institution: 'USC Information Sciences Institute',
    milestones: [
      {
        id: 'usc-m1',
        title: 'Safety evaluation suite',
        description: 'Release red-teaming and eval harness for autonomous lab agents',
        targetDate: new Date('2024-06-30'),
        fundingRequired: 250000,
        completed: false,
      },
      {
        id: 'usc-m2',
        title: 'National lab pilot',
        description: 'Deploy agents on a DoE materials beamline in collaboration with lab staff',
        targetDate: new Date('2024-09-30'),
        fundingRequired: 400000,
        completed: false,
      },
    ],
  },
  {
    id: 'mit-carbon-1',
    title: 'Direct Air Carbon Capture Network',
    description: 'Scalable atmospheric CO₂ capture using metal-organic frameworks (MOFs)',
    longDescription:
      'MIT Climate Lab is developing novel metal-organic frameworks that capture CO₂ from ambient air with unprecedented efficiency. Modular capture units can operate near renewable energy sources and share adsorption data openly so other labs can replicate results. Early prototypes indicate 70% lower energy requirements compared to incumbent solutions, unlocking gigaton-scale removal pathways.',
    category: 'Climate Modeling',
    imageUrl:
      'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=1600&q=80',
    videoUrl: 'https://www.youtube.com/embed/s9L62ea4eRg',
    fundingGoal: 500000,
    currentFunding: 342500,
    stakedAmount: 285000,
    backers: 1247,
    daysLeft: 22,
    creator: '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb6',
    createdAt: new Date('2024-01-15'),
    matchingPool: 75000,
    quadraticScore: 8.7,
    acceptedTokens: ['USDC', 'DAI', 'NOVA'],
    researchArea: 'Climate Engineering',
    institution: 'MIT Climate Lab',
    milestones: [
      {
        id: 'mit-m1',
        title: 'Prototype development',
        description: 'Complete first working prototype of the MOF capture module',
        targetDate: new Date('2024-06-01'),
        fundingRequired: 150000,
        completed: false,
      },
    ],
  },
  {
    id: 'stanford-quantum-1',
    title: 'Topological Quantum Error Correction',
    description: 'Fault-tolerant quantum computing through topological qubits',
    longDescription:
      'Stanford Quantum Lab is pioneering topological quantum error correction methods that leverage anyonic braiding to create inherently fault-tolerant quantum gates. The program open-sources simulation tooling, publishes benchmark datasets, and collaborates with USC ISI to test compiler optimizations. Error rates have improved three orders of magnitude over surface codes in early simulations.',
    category: 'Quantum Information',
    imageUrl:
      'https://images.unsplash.com/photo-1635070041409-e63e783ce3c1?auto=format&fit=crop&w=1600&q=80',
    videoUrl: 'https://www.youtube.com/embed/YgvJGV3PkwQ',
    fundingGoal: 750000,
    currentFunding: 425000,
    stakedAmount: 380000,
    backers: 892,
    daysLeft: 45,
    creator: '0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199',
    createdAt: new Date('2024-01-20'),
    matchingPool: 100000,
    quadraticScore: 9.2,
    acceptedTokens: ['USDC', 'DAI', 'USDT', 'NOVA'],
    researchArea: 'Theoretical Physics',
    institution: 'Stanford Quantum Lab',
    milestones: [
      {
        id: 'stanford-m1',
        title: 'Algorithm testing',
        description: 'Complete testing on USC ISI/Stanford quantum simulators',
        targetDate: new Date('2024-07-15'),
        fundingRequired: 200000,
        completed: false,
      },
    ],
  },
  {
    id: 'hopkins-neuro-1',
    title: 'BrainBridge Neural Restoration',
    description: 'High-resolution brain-computer interfaces for motor function recovery',
    longDescription:
      'Johns Hopkins Applied Physics Lab is developing flexible graphene electrode arrays that decode motor intentions with millisecond precision. The team collaborates with rehabilitation clinicians and publishes firmware, safety protocols, and anonymized datasets so others can validate outcomes. Early trials demonstrate 95% task accuracy in robotic limb control for three patients.',
    category: 'Neuroscience Interfaces',
    imageUrl:
      'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=1600&q=80',
    videoUrl: 'https://www.youtube.com/embed/5DWrjTBuCKc',
    fundingGoal: 1000000,
    currentFunding: 567000,
    stakedAmount: 512000,
    backers: 1567,
    daysLeft: 60,
    creator: '0x90F79bf6EB2c4f870365E785982E1f101E93b906',
    createdAt: new Date('2024-02-01'),
    matchingPool: 150000,
    quadraticScore: 9.5,
    acceptedTokens: ['USDC', 'DAI', 'USDT', 'NOVA'],
    researchArea: 'Neurotechnology',
    institution: 'Johns Hopkins APL',
    milestones: [
      {
        id: 'hopkins-m1',
        title: 'Clinical trial enrollment',
        description: 'Begin Phase 1 clinical trials with three new participants',
        targetDate: new Date('2024-09-01'),
        fundingRequired: 400000,
        completed: false,
      },
    ],
  },
  {
    id: 'biosecurity-rapid-1',
    title: 'Programmable Biosurveillance Platform',
    description: 'Portable metagenomic sequencing for early pathogen detection',
    longDescription:
      'The Broad Institute and USC ISI biosafety group are co-developing a rapid biosurveillance platform that combines nanopore sequencing with onboard machine learning. The system can detect emerging pathogens in under 60 minutes and automatically share anonymized genomic signatures with public health networks. Open protocols ensure labs globally can manufacture cartridges and audit analysis pipelines.',
    category: 'Biosecurity & Health',
    imageUrl:
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1600&q=80',
    videoUrl: 'https://www.youtube.com/embed/ZOoUIlLmxf4',
    fundingGoal: 680000,
    currentFunding: 352000,
    stakedAmount: 300000,
    backers: 1189,
    daysLeft: 27,
    creator: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
    createdAt: new Date('2024-02-18'),
    matchingPool: 110000,
    quadraticScore: 8.9,
    acceptedTokens: ['USDC', 'NOVA'],
    researchArea: 'Biosecurity',
    institution: 'Broad Institute x USC ISI',
    milestones: [
      {
        id: 'biosecurity-m1',
        title: 'Field validation kit',
        description: 'Ship 25 pilot units with validated reagent supply chain',
        targetDate: new Date('2024-08-01'),
        fundingRequired: 220000,
        completed: false,
      },
    ],
  },
  {
    id: 'fusion-diagnostics-1',
    title: 'AI Diagnostics for Inertial Fusion',
    description: 'Real-time anomaly detection for fusion target implosions',
    longDescription:
      'Lawrence Livermore National Laboratory scientists are training physics-informed neural networks on terabytes of National Ignition Facility shot data. The models identify failure modes in under 200 milliseconds, giving operators the ability to adjust future shot configurations faster. USC ISI contributes scalable inference infrastructure, and all calibration data is released for the broader fusion community.',
    category: 'Energy & Fusion',
    imageUrl:
      'https://images.unsplash.com/photo-1564325724739-bae0bd08762c?auto=format&fit=crop&w=1600&q=80',
    videoUrl: 'https://www.youtube.com/embed/2kh6Ik4-yag',
    fundingGoal: 820000,
    currentFunding: 505000,
    stakedAmount: 460000,
    backers: 1342,
    daysLeft: 31,
    creator: '0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65',
    createdAt: new Date('2024-03-05'),
    matchingPool: 140000,
    quadraticScore: 9.0,
    acceptedTokens: ['USDC', 'DAI', 'NOVA'],
    researchArea: 'Plasma Physics',
    institution: 'Lawrence Livermore National Laboratory',
    milestones: [
      {
        id: 'fusion-m1',
        title: 'Dataset release',
        description: 'Publish annotated implosion dataset for community benchmarking',
        targetDate: new Date('2024-10-01'),
        fundingRequired: 260000,
        completed: false,
      },
    ],
  },
  {
    id: 'orbital-systems-1',
    title: 'Orbital Debris Laser Tracking',
    description: 'Ground-to-space optical system to monitor centimeter-scale debris',
    longDescription:
      'Caltech Space Systems Lab is constructing a coherent laser ranging array that can track centimeter-scale orbital debris in low Earth orbit. Accurate tracking data is critical to keep research satellites safe and is shared openly with the global space science community. The project collaborates with USC ISI aerospace researchers on simulation tooling and data dissemination.',
    category: 'Space & Planetary Science',
    imageUrl:
      'https://images.unsplash.com/photo-1454391304352-2bf4678b1a7a?auto=format&fit=crop&w=1600&q=80',
    videoUrl: 'https://www.youtube.com/embed/h8FPG6BDb0Q',
    fundingGoal: 610000,
    currentFunding: 298000,
    stakedAmount: 255000,
    backers: 978,
    daysLeft: 39,
    creator: '0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f',
    createdAt: new Date('2024-03-12'),
    matchingPool: 90000,
    quadraticScore: 8.2,
    acceptedTokens: ['USDC', 'DAI', 'NOVA'],
    researchArea: 'Aerospace Engineering',
    institution: 'Caltech Space Systems Lab',
    milestones: [
      {
        id: 'orbital-m1',
        title: 'Prototype telescope array',
        description: 'Complete installation of three synchronized ground stations',
        targetDate: new Date('2024-11-15'),
        fundingRequired: 210000,
        completed: false,
      },
    ],
  },
];
